sudo: required

language: generic

services:
  - docker

before_install:
  - source version.sh
  - echo $VERSION
  - docker build -t smarthomefans/iobroker .
  - docker build -t smarthomefans/iobroker:taobao  --build-arg MIRROR=Taobao .
  - docker tag smarthomefans/iobroker smarthomefans/iobroker:$VERSION
  - docker tag smarthomefans/iobroker:taobao smarthomefans/iobroker:taobao-$VERSION
  # - docker build -t smarthomefans/iobroker:v10 --build-arg IOBROKER_VERSION=$VERSION --build-arg NODE_VERSION=10.3.0  .
  # - docker tag smarthomefans/iobroker:v10 smarthomefans/iobroker:$VERSION-v10

script:
  - docker run -d smarthomefans/iobroker:latest
  - sleep 15
  - docker ps | grep latest
  - docker run -d smarthomefans/iobroker:taobao
  - sleep 15
  - docker ps | grep taobao
  - docker run -d smarthomefans/iobroker:$VERSION
  - sleep 15
  - docker ps | grep latest

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push smarthomefans/iobroker;
    fi